#pragma once

#include <vector>
#include <string>


using namespace std;

#ifndef TESTCASES_H_INCLUDED
#define TESTCASES_H_INCLUDED

vector<string> words3 =
{ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaab",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaac" };
vector<string> parts3 =
{ "aaaaa",
 "bbbbb",
 "a",
 "aa",
 "aaaa",
 "AAAAA",
 "aaa",
 "aba",
 "aaaab",
 "c",
 "bbbb",
 "d",
 "g",
 "ccccc",
 "B",
 "C",
 "P",
 "D" };
vector<string> words ={ "neuroses",
 "myopic",
 "sufficient",
 "televise",
 "coccidiosis",
 "gules",
 "during",
 "construe",
 "establish",
 "ethyl" };
vector<string> parts = { "aaaaa",
 "Aaaa",
 "E",
 "z",
 "Zzzzz",
 "a",
 "mel",
 "lon",
 "el",
 "An",
 "ise",
 "d",
 "g",
 "wnoVV",
 "i",
 "IUMc",
 "P",
 "KQ",
 "QfRz",
 "Xyj",
 "yiHS" };

vector<string> words4 = { "Norris",
"random",
"bushmaster",
"disposal",
"territorial",
"obstinate",
"eigenstate",
"momentum",
"boatload",
"citrus",
"discriminatory",
"miscible",
"sadist",
"nasty",
"suey",
"sacrilegious",
"substrate",
"doubleheader",
"evade",
"halocarbon",
"backplate",
"thespian",
"folly",
"sparling",
"ambiance",
"indeterminable",
"gunny",
"exorbitant",
"protrude",
"Bissau",
"Korea",
"salute",
"Godfrey",
"belief",
"pate",
"Mackey",
"sing",
"yaw",
"raptor",
"morass",
"c",
"Elisabeth",
"mesmeric",
"uproot",
"buckle",
"cannonball",
"cataract",
"already",
"clout",
"strategic",
"down",
"marvelous",
"councilwomen",
"FL",
"billionth",
"from",
"concussion",
"flimsy",
"stuck",
"reciprocate",
"hellish",
"feather",
"papaw",
"sobriety",
"glow",
"Wyatt",
"Goodrich",
"Preston",
"tripe",
"arum",
"hologram",
"tractor",
"capsize",
"McCracken",
"trig",
"Athens",
"char",
"experience",
"psychopath",
"prevail",
"densitometer",
"Mayflower",
"event",
"vacuole",
"Hendrickson",
"Edgerton",
"instead",
"twelfth",
"palazzi",
"passerby",
"ball",
"monastery",
"courtesy",
"coverage",
"picayune",
"besmirch",
"conscious",
"halve",
"impediment", "cookbook" };

vector<string> parts4 = { "WjN","gr","zWo","qVRJI","oGtu","Rtae","weY","vtJVN",
             "UpvGj",
             "pkB",
             "iTtP",
             "pbW",
             "yvSlm",
             "ryCd",
             "eDCM",
             "fjpDW",
             "gbb",
             "OF","vdz",
             "x",
             "NPS",
             "kuU",
             "irU",
             "qkEn",
             "aDpIy",
             "oOZYR",
             "PG",
             "plTjl",
             "zmpP",
             "C",
             "ZO",
             "vwQKC",
             "K",
             "S",
             "jod",
             "W",
             "gYOTF",
             "ObN",
             "WWW",
             "Zj",
             "k",
             "dYKay",
             "sZpnz",
             "uZpG",
             "w",
             "vKELP",
             "UD",
             "PdD",
             "GeS",
             "SpkW",
             "BKb",
             "VjVF",
             "DbKWv",
             "mHSo",
             "zyUPs",
             "fzE",
             "DHT",
             "JiVx",
             "fDI",
             "xC",
             "JFEU",
             "KJdW",
             "pYf",
             "ajIIy",
             "B",
             "J",
             "N",
             "VwM",
             "V",
             "mIzeb",
             "QMDe",
             "ycVQU",
             "uw",
             "j",
             "bpzvj",
             "mv",
             "z",
             "Ct",
             "nJ",
             "Yoj",
             "in",
             "YQ",
             "UfSS",
             "Dn",
             "IxDg",
             "ryfh",
             "KjaGa",
             "Xfz",
             "FVXL",
             "QCk",
             "RyAJ",
             "vIEM",
             "pnnRC",
             "Qj",
             "egG",
             "a",
             "e",
             "i",
             "incPb", "Ucy" };

vector<string> words2 = { "Apple","Melon","Orange", "Watermelon","twalfth" };
vector<string> parts2 = { "a","mel","lon","el","An", "waY","w" };

#endif // TESTCASES_H_INCLUDED
